---
title: "data_cleaning"
#output: html_notebook
---
# PA Data Cleaning

## Clear environment
```{r}
rm(list=ls(all=TRUE))
```

## Define User
```{r}
# User="Matias"
User="Sarah"
# User="Abbey"

if(!exists('handl_OneDrive'))
{
  if(User=="Matias") source('C:/Users/myb/OneDrive - Department of Primary Industries and Regional Development/Matias/Analyses/SOURCE_SCRIPTS/Git_other/handl_OneDrive.R')
  if(User=="Sarah")    handl_OneDrive=function(x)paste('C:/Users/S.Jesso/Documents/GitHub',x,sep='/')
  if(User=="Abbey")    handl_OneDrive=function(x)paste('C:/Users',Usr,'OneDrive - Department of Primary Industries and Regional Development/Matias',x,sep='/')
}

```

## Load Packages
```{r}
library(tidyverse)
library(dplyr)
library(readxl)
library(ggrepel)
library(ggpubr)
library(rlang)
library(MASS)
library(ggmosaic)
library(Hmisc)
library(gridExtra)
library(stringr)
library(extdplyr)
library(ggpubr)
library(ggridges)
library(vegan)
#library(pairwiseAdonis)
library(overlapping)
library(tweedie)
library(mgcv)
library(emmeans)  #for model predictions
library(doParallel)
library(flextable)
library(webshot)
library(visNetwork)
library(ozmaps)
library(sf)
library(ggpmisc)
library(forecast)
library(performance)
library(ggforce)
library(scales)
library(igraph)
library(janitor)

options(stringsAsFactors = FALSE,dplyr.summarise.inform = FALSE) 
```

## Source Constants and Functions
```{r}
source("data_cleaning_functions.R")
source("data_cleaning_constants.R")
```


## Define Data Dump
```{r}
Event.Mes.data.dump <- 'Abbey_Sarah'
```

## Loop to read in and clean data
```{r}
if(Event.Mes.data.dump=='Abbey_Sarah')
{
  #1. read in  data
  #1.1. gillnet
  setwd(
    'C:/Users/S.Jesso/OneDrive - Department of Primary Industries And Regional Development/Final_EMobs/Outputs16-01-23/Gillnet'
  )
  filenames <- list.files(pattern = '*.csv')
  dummy.GN <- lapply(filenames, read.csv, skip = 4)
  #1.2. longline
  setwd(
    'C:/Users/S.Jesso/OneDrive - Department of Primary Industries And Regional Development/Final_EMobs/Outputs16-01-23/Longline'
  )
  filenames <- list.files(pattern = '*.csv')
  dummy.LL <- lapply(filenames, read.csv, skip = 4)
  
  #2. put data in standard format
  #2.1. gillnet
    Video.net.interaction = Video.net.maxN = Video.net.obs=vector('list',length(dummy.GN))

    for (i in 1:length(dummy.GN))
    {
      #Call RenameColumn function to deal with spelling errors and make names same as Jacks import
      dummy.GN[[i]] <- RenameColumn(dummy.GN[[i]])
      
      #REVIEW:Fix for some dfs in dummy.GN missing position column
      if (!'Position' %in% names(dummy.GN[[i]]))
        dummy.GN[[i]]$Position = NA
      
      Video.net.interaction[[i]] <- dummy.GN[[i]] %>%
        filter(is.na(MaxN)) %>%
        dplyr::select(all_of(interaction.names)) %>%
        CategoriseComment() %>%
        mutate(
          Number = ifelse(Number == 'AD', NA, Number),
          No.haul = Alt.species == "no haul",
          No.fish = Alt.species == "no fish",
          Species = case_when(
            Species == "" ~ as.character(Alt.species),
            is.na(Species) ~ as.character(Alt.species),
            TRUE ~ as.character(Species)
          ),
          Escape = ifelse(
            grepl("^\\d|^\\<", Escape),
            gsub("([0-9]+).*$", "\\1", Escape),
            ''
          ),
          Interaction = AssignInteractions(Interaction)
        )

    Video.net.maxN[[i]] <- dummy.GN[[i]] %>%
      RenameColumn() %>%
      dplyr::select(all_of(maxn.names)) %>%
      CategoriseComment() %>%
      mutate(Species = case_when(
        Species == "" ~ as.character(Alt.species),
        is.na(Species) ~ as.character(Alt.species),
        TRUE ~ as.character(Species)
      ))
    
 #  #   Video.net.obs[[i]]=dummy.GN[[i]]%>%
 #  #     rename("Time (mins)"="Time..mins.",
 #  #            "Period time (mins)"="Period.time..mins.")%>%
 #  #     mutate(observation=Escape,
 #  #            Camera.stopped=ifelse(observation%in%c('end-no haul',"end no haul","end before haul",
 #  #                                                   'CAMERA STOPS',"end","ended before haul",
 #  #                                                   "finish before haul","no haul"," no haul"),'Yes','No'),
 #  #            Got.dark=grepl('dark',tolower(observation)),
 #  #            observation=case_when(observation=="7 legged startfish"~"seven legged startfish",
 #  #                                  grepl("\\d", observation)~'',
 #  #                                  Got.dark=='TRUE'~'',
 #  #                                  observation%in%c("squid","SQUID")~"Squid",
 #  #                                  observation%in%c("cuttle fish","CUTTLEFISH","cuttlefish-attrached to camera")~"cuttlefish",
 #  #                                  observation%in%c("unidentifiable school","UNKNONW FISH")~"unknown fish",
 #  #                                  observation%in%c("australian fur seal","sealion")~"sea lion",
 #  #                                  observation=="commernat"~"commorant",
 #  #                                  is.na(observation)~"",
 #  #                                  observation=="garnard"~"gurnard",
 #  #                                  observation%in%c("bait schiool","school","School","bait fish","bait school","larger baitfish")~"baitfish",
 #  #                                  observation%in%DROP~'',
 #  #                                  TRUE~as.character(Escape)),
 #  #            code=Code)%>%
 #  #     dplyr::select(all_of(c(observation.names,'Got.dark','Camera.stopped')))
 #  #   
 #  #   print(i)
 #  #   
    }
  Video.net.interaction <- do.call(rbind,Video.net.interaction)%>% 
   filter(!Species%in%c(""," ") & No.haul==FALSE & No.fish==FALSE)
  Video.net.maxN=do.call(rbind,Video.net.maxN)%>%
   filter(!is.na(MaxN))
  # Video.net.obs=do.call(rbind,Video.net.obs)%>%
  #   filter(!observation=='')
  
  #2.2. longline
  Video.longline.interaction = Video.longline.maxN = Video.longline.obs =
    vector('list', length(dummy.LL))
  for (i in 1:length(dummy.LL))
  {
    #Call RenameColumn function to deal with spelling errors and make names same as Jacks import
    dummy.LL[[i]] <- RenameColumn(dummy.LL[[i]])
    
    #REVIEW:Fix for some dfs in dummy.LL missing position column
    if (!'Position' %in% names(dummy.LL[[i]]))
      dummy.LL[[i]]$Position = NA
    
    Video.longline.interaction[[i]] <-  dummy.LL[[i]] %>%
      filter(is.na(MaxN)) %>%
      dplyr::select(all_of(interaction.names)) %>%
      CategoriseComment() %>%
      mutate(
        Number = ifelse(Number == 'AD', NA, Number),
        No.haul = Alt.species == "no haul",
        No.fish = Alt.species == "no fish",
        Species = case_when(
          Species == "" ~ as.character(Alt.species),
          is.na(Species) ~ as.character(Alt.species),
          TRUE ~ as.character(Species)
        ),
        Escape = ifelse(grepl("\\d", Escape), gsub("([0-9]+).*$", "\\1", Escape), ''),
        Interaction = AssignInteractions(Interaction)
      )

    Video.longline.maxN[[i]] = dummy.LL[[i]] %>%
      RenameColumn() %>%
      dplyr::select(all_of(maxn.names)) %>%
      CategoriseComment() %>%
      mutate(Species = case_when(
        Species == "" ~ as.character(Alt.species),
        is.na(Species) ~ as.character(Alt.species),
        TRUE ~ as.character(Species)
      ))
    

    #   Video.longline.obs[[i]]=dummy.LL[[i]]%>%
    #     rename("Time (mins)"="Time..mins.",
    #            "Period time (mins)"="Period.time..mins.")%>%
    #     mutate(observation=Escape,
    #            Camera.stopped=ifelse(observation%in%c('end-no haul',"end no haul","end before haul",
    #                                                   'CAMERA STOPS',"end","ended before haul",
    #                                                   "finish before haul","no haul"," no haul"),'Yes','No'),
    #            Got.dark=grepl('dark',tolower(observation)),
    #            observation=case_when(observation=="7 legged startfish"~"seven legged startfish",
    #                                  grepl("\\d", observation)~'',
    #                                  Got.dark=='TRUE'~'',
    #                                  observation%in%c("squid","SQUID")~"Squid",
    #                                  observation%in%c("cuttle fish","CUTTLEFISH","cuttlefish-attrached to camera")~"cuttlefish",
    #                                  observation%in%c("unidentifiable school","UNKNONW FISH","fish sp unsure ","unknown  school ")~"unknown fish",
    #                                  observation%in%c("australian fur seal","sealion")~"sea lion",
    #                                  observation=="commernat"~"commorant",
    #                                  is.na(observation)~"",
    #                                  observation=="garnard"~"gurnard",
    #                                  observation%in%c("bait schiool","school","School","bait fish","bait school","larger baitfish")~"baitfish",
    #                                  observation%in%DROP~'',
    #                                  TRUE~as.character(Escape)),
    #            code=Code)%>%
    #     dplyr::select(all_of(c(Video.net.obs.names,'Got.dark','Camera.stopped')))
    #
    #   print(i)
    #
  }
  Video.longline.interaction = do.call(rbind, Video.longline.interaction) %>%
    filter(!Species %in% c(" ", "") & No.haul == FALSE & No.fish == FALSE)
  Video.longline.maxN=do.call(rbind,Video.longline.maxN)%>%
    filter(!is.na(MaxN))%>%
    rename(Max.N=MaxN)
  # Video.longline.obs=do.call(rbind,Video.longline.obs)%>%
  #   filter(!observation=='')%>%
  #   rename(Observation=observation,
  #          optcode=OpCode)
  
  
}

```
## Checks
```{r}
llchecklist <- subset(Video.longline.interaction, is.na(Species) & No.haul==FALSE & No.fish==FALSE)
llchecklist
```
```{r}
sp.in.net.inter <- unique(Video.net.interaction$Species)
sp.in.net.inter
```
```{r}
sp.in.ll.inter <- unique(Video.longline.interaction$Species)
sp.in.ll.inter
```
```{r}
countopcodesll <- as.list(unique(Video.longline.interaction$OpCode))
length(countopcodesll)
### SHOULD BE 156 and unique sp in vli should have octopus
```
```{r}
sp.in.ll.maxn <- unique(Video.longline.maxN$Species)
sp.in.ll.maxn
```

```{r}
llmaxncheck <- subset(Video.longline.maxN, Species==""|is.na(Species))
llmaxncheck
```
```{r}
sp.in.net.maxn <- unique(Video.net.maxN$Species)
sp.in.net.maxn
```
```{r}
gnmaxncheck <- subset(Video.net.maxN, Species==""|is.na(Species))
gnmaxncheck
```
# check to compare unique sp in inter and maxn dfs
## Alt species such as snail, turtle, bird are OK.
```{r}
setdiff(sp.in.ll.inter, sp.in.ll.maxn)
setdiff(sp.in.ll.maxn, sp.in.ll.inter)
```
```{r}
check.net.maxn <- setdiff(sp.in.net.inter, sp.in.net.maxn)
check.net.maxn
checklist.net.maxn <- Video.net.maxN %>% filter(Species=="mosaica")
checklist.net.maxn
```
```{r}
check.net.maxn.2 <- setdiff(sp.in.net.maxn, sp.in.net.inter)
check.net.maxn.2
```
## List of points that have no interaction assigned
```{r}
gn.no.interaction <- Video.net.interaction %>% filter(Interaction == "Missing data")
gn.no.interaction
unique(gn.no.interaction$Species)
crap <- gn.no.interaction %>% filter(Species=="baitfish")
unique(crap$OpCode)
## Alt species are OK
```
```{r}
ll.no.interaction <- Video.longline.interaction %>% filter(Interaction == "Missing data")
ll.no.interaction
unique(ll.no.interaction$Species)
crap1 <- ll.no.interaction %>% filter(Species%in%c("baitfish"))
unique(crap1$OpCode)
```
List EMobs to check
```{r}
checklist <- c("Peacfull_Gillnet_PA0058_Camera_#20_Pempheris_affins_enedmic_to_eastcoast",
               "Lancerlin_Longline_Pa0143_Camera_#8_Polyprion_americanus_unlikely",
               "Albany_Longline_PA0113_Camera_#8_Plectorhinchus_caeruleonothus_unlikely",
               "Albany_Longline_PA0118_Camera_#02,Albany_Longline_PA0118_Camera_#05_Caranx_ignobilis_unlikely",
               "Lancerlin_Gillnet_PA0036_Camera_#8_lata",
"Augusta_Gillnet_PA0006_Camera_#19_Augusta_Gillnet_PA0006_Camera_#19_Augusta_Gillnet_PA0006_Camera_#19_Augusta_Gillnet_PA0019_Camera_#1_Augusta_Gillnet_PA0019_Camera_#5_Pentapotus_vitta_unlikely"
               )
```



