---
title: "Recortes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Gross Value Added
The GVA of the TDGDLF was calculated as follows:
$$GVA=R - C + T + W$$
where $R$ is the annual revenue generated by the TDGDLF; $C$ is the annual costs incurred by the TDGDLF; $T$ is the annual taxes payed by the TDGDLF; and $W$ are the annual wages paid by the TDGDLF.

$$R=\sum\limits_{i=1}pf_{i} \bar{l_{i}}$$
where $pf_{i}$ is the price paid to TDGDLF fishers per kg for species $i$ (trunks for sharks, whole fish for scalefish).

$$C=c\  n_{TDGDLF}$$
where $c$ is the annual costs (minimum and maximum) incurred by an average boat operating in the TDGDLF (vessel and gear repairs and maintenance, vessel lease/mortgage, fuel and lubricants, food, packaging, ice, administration), obtained from the socio-economic survey; and $n_{TDGDLF}$ is the total number of fishing vessels operating in the TDGDLF, obtained from the Department's databases.


$$T=t\  n_{TDGDLF}$$
where $t$ is the annual tax (minimum and maximum) paid by an average boat operating in the TDGDLF, obtained from the socio-economic survey.

$$W=w\  n_{TDGDLF}$$
where $w$ is the annual wages (minimum and maximum) paid by an average boat operating in the TDGDLF, obtained from the socio-economic survey.
